version: "3.1"
services:
  kniot-scrapper:
    build:
      context: .
    environment:
      - XML_STORE_PATH=dumps/
      - MONGO_URL=localhost
      - MONGO_PORT=27017
    container_name: kniot-scrapper
    hostname: kniot-scrapper
    restart: unless-stopped
    volumes:
      - dumps:/usr/src/app/dumps
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
        - database:/data/db
    ports:
        - 27017:27017
    restart: unless-stopped

volumes:
  dumps:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./dumps
  database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./database