version: "3.1"
services:
  kniot-scrapper:
    build:
      context: .
    environment:
      - XML_STORE_PATH=dumps/
      - MONGO_URL=localhost
      - MONGO_PORT=27017
      - SE_MODE=False
    container_name: kniot-scrapper
    network_mode: "host"
    hostname: kniot-scrapper
    restart: unless-stopped
    volumes:
      - ./dumps:/usr/src/app/dumps
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  mongodb-scrapper:
    image : mongo
    container_name: mongodb-scrapper
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
        - ./database:/data/db
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    ports:
        - 27017:27017
    restart: unless-stopped

# volumes:
#   dumps:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: ./dumps
#   database:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: ./database