# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test-suite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 12 1/7 * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build with Docker
      run: docker build -t erlichsefi/israeli-supermarket-scarpers:test --target test .
    - name: Test with pytest
      run: docker run --rm --name test-run erlichsefi/israeli-supermarket-scarpers:test
